spring:
  profiles:
    active: local
#    active: prd
  application:
    name: SISUL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.219.165:3306/sisul?serverTimezone=UTC
    username: sisul
    password: sisul20@!
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: Asia/Seoul
  devtools:
    restart:
      log-condition-evaluation-delta: false
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    host: smtp.gmail.com
    port: 587
    username: jayur830
    password: bzqqawbtastpmogi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org.sisul.material_management: info
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      show_sql: true
      format_sql: true
---
server:
  port: 9100
spring:
  config:
    activate:
      on-profile: prd
  jpa:
    properties:
      show_sql: false
      format_sql: false
